export const INCREMENT_COUNT = "INCREMENT_COUNT";
export const DECREMENT_COUNT = "DECREMENT_COUNT";
export const INCREMENT_COUNT_BY = "INCREMENT_COUNT_BY";
export const DECREMENT_COUNT_BY = "DECREMENT_COUNT_BY";
export const RESET_COUNTER = "RESET_COUNTER";
